# Generated by Django 3.2.4 on 2021-07-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0007_auto_20210701_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='profile',
        ),
        migrations.AddField(
            model_name='content',
            name='profile',
            field=models.ManyToManyField(blank=True, to='mydiary.Profile'),
        ),
    ]
