# Generated by Django 3.2.4 on 2021-07-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0011_content_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(default='', max_length='300'),
        ),
    ]
